# Generated by Django 4.0.4 on 2022-04-17 22:47

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
